# Generated by Django 4.2.29 on 2026-03-06 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_logs', to='contracts.contract')),
            ],
        ),
    ]
