# Generated by Django 6.0.3 on 2026-03-06 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='contracts.contract'),
        ),
    ]
